services:
  - type: web
    name: pokemon-card-scanner
    env: python
    region: oregon
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT web_app:app --timeout 120 --workers 1"
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.9"
    autoDeploy: false
    healthCheckPath: /api/health